/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalPhase;

import java.awt.Toolkit;
import java.io.FileWriter;
import java.io.IOException;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Omar Alomory
 */
public class MainMenu extends javax.swing.JFrame {

    private ArrayList<String> foodMenu;
    private ArrayList<Double> foodPrice;
    private ArrayList<Integer> quantity;
    private ArrayList<String> result = new ArrayList();
    private FileWriter receiptFile = null;
    private double total = 0;
    private Login log;
    private static int count = 1;

    public MainMenu() {
       log = new Login();
        foodMenu = new ArrayList();
        foodPrice = new ArrayList();
        foodMenu.add("Burger[Big]");
        foodMenu.add("Burger[Small]");
//        foodMenu.add("Rice");
//        foodMenu.add("Chicken Rice");
        foodMenu.add("Chicken");
        foodMenu.add("Salad");
        foodMenu.add("Apple Juice");
        foodMenu.add("Orange Juice");
        foodMenu.add("Green Tea");
        foodMenu.add("Tea O");
        foodPrice.add(4.99);
        foodPrice.add(2.99);
//        foodPrice.add(0.99);
//        foodPrice.add(5.45);
        foodPrice.add(7.99);
        foodPrice.add(0.99);
        foodPrice.add(3.50);
        foodPrice.add(3.00);
        foodPrice.add(2.00);
        foodPrice.add(2.50);
        quantity = new ArrayList();
        for (int i = 0; i < foodMenu.size(); i++) {
            quantity.add(0);
        }

        initComponents();
        totalTextField.setText(total + "");
        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res.png")));
        printOrderHeader();
        printMenu();
    }

    public MainMenu(ArrayList<String> foodMinu, ArrayList<Double> foodPrice, Login log) {
        this.log = log;
        this.foodMenu = new ArrayList(foodMinu);
        this.foodPrice = new ArrayList(foodPrice);
        this.quantity = new ArrayList();
        for (int i = 0; i < foodMenu.size(); i++) {
            quantity.add(0);
        }

        initComponents();
        totalTextField.setText(total + "");
        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res.png")));
        printOrderHeader();
        printMenu();
    }

    public void printOrderHeader() {
        Date date = new Date();
        jTextArea2.setText("Date:" + date.getDate() + "/" + (date.getMonth() + 1) + "/" + (date.getYear() + 1900)
                + "  -  Time: " + date.getHours() + " : " + date.getMinutes() + "\n\n"
                + "=================================\n"
                + "Item Name      Quantity     Total\n"
                + "=================================\n");
    }

    public void printMenu() {
        jTextArea1.setText("");
        jTextArea1.setText( "===============================\n"
                + "|  Items                 Price |\n"
                + "===============================\n");
        String result = "";
        for (int i = 0; i < foodMenu.size(); i++) {
            result = String.format("(%-2d). %-18s: %.2f", (i + 1),  foodMenu.get(i),foodPrice.get(i));
            jTextArea1.setText(jTextArea1.getText() + result + "\n");
//            jTextArea1.append("\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ItemNoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        infoButton = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        printReceiptButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group H Restaurant");
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/restop.png")));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Main Menu");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 255), null, null));

        LogOutButton.setText("Login");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        ItemNoTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                ItemNoTextFieldCaretUpdate(evt);
            }
        });

        jLabel2.setText("Item No");

        jLabel3.setText("Quantity");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTextArea2);
        jTextArea2.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Menu");

        jLabel5.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Your Order");

        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-question-mark-30.png"))); // NOI18N
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLabel.setBorder(null);

        totalTextField.setEditable(false);

        jLabel6.setText("Total =");

        printReceiptButton.setText("Print Receipt");
        printReceiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReceiptButtonActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainInterface.png"))); // NOI18N
        jLabel9.setText("fdsajklsjdf");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogOutButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ItemNoTextField)
                                        .addComponent(quantityTextField)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(printReceiptButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 969, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogOutButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemNoTextField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        this.dispose();
        LoginInterface login = new LoginInterface(foodMenu, foodPrice,log);
        login.setVisible(true);

    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            int itemNo = Integer.parseInt(ItemNoTextField.getText());
            int qntty = Integer.parseInt(quantityTextField.getText());
            total = 0;
            quantity.set(itemNo - 1, quantity.get(itemNo - 1) + qntty);

            jTextArea2.setText("");
            printOrderHeader();
            String text = "";
            for (int i = 0; i < foodMenu.size(); i++) {
                if (quantity.get(i) > 0) {

                    text = String.format("%-18s %-7d  %.2f",foodMenu.get(i) ,quantity.get(i), (foodPrice.get(i) * quantity.get(i)) );
                    jTextArea2.setText(jTextArea2.getText() + text + "\n");
                    //result.add( String.format("(%d). %-30s %.2f", (count), foodMenu.get(i),(foodPrice.get(i)*quantity.get(i))));
                    total = total + (foodPrice.get(i) * quantity.get(i));
                    totalTextField.setText(String.format("% .2f", total));
                }

            }
            ItemNoTextField.setText("");
            quantityTextField.setText("");

        } catch (Exception p) {
            JOptionPane.showMessageDialog(null, p.toString(), p.getClass().getSimpleName(), JOptionPane.ERROR_MESSAGE);
            ItemNoTextField.setText("");
            quantityTextField.setText("");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Delete:\n"
                + "1. To delete item without specifying quantity, it will delete the whole item from list\n"
                + "2. If quantity entered it will delete the specified quantity\n\n"
                + "Clear:\n"
                + "1. will delete the whole list you ordered already\n",
                "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_infoButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            int index = Integer.parseInt(ItemNoTextField.getText());
            int qntty = Integer.parseInt(quantityTextField.getText());

            if (quantity.get(index - 1) - qntty < 0) {
                throw new MyExceptions("Quantity can not be less that zero");
            }
            if (quantity.get(index - 1) - qntty >= 0) {
                quantity.set(index - 1, quantity.get(index - 1) - qntty);
                total = 0;
                printOrderHeader();
                String text = "";
                for (int i = 0; i < foodMenu.size(); i++) {
                    if (quantity.get(i) > 0) {
                        text = String.format("%-18s %-7d  %.2f",foodMenu.get(i) ,quantity.get(i), (foodPrice.get(i) * quantity.get(i)) );
                        jTextArea2.setText(jTextArea2.getText() + text + "\n");

                    }
                    total = total + (foodPrice.get(i) * quantity.get(i));
                    totalTextField.setText(String.format("% .2f", total));
                }
            }
            ItemNoTextField.setText("");
            quantityTextField.setText("");
        } catch (Exception a) {
            JOptionPane.showMessageDialog(null, a.getMessage(), a.getClass().getSimpleName(), JOptionPane.ERROR_MESSAGE);
                        ItemNoTextField.setText("");
            quantityTextField.setText("");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
                int cusomerRespond = JOptionPane.showConfirmDialog(null, "You are about to clear your order list, confirm?", "Clear Order",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (cusomerRespond == JOptionPane.YES_OPTION) {
                    printOrderHeader();
        for (int i = 0; i < quantity.size(); i++) {
            quantity.set(i, 0);
        }
        total = 0;
        totalTextField.setText(total + "");
        } else if (cusomerRespond == JOptionPane.NO_OPTION) {

        }
        



    }//GEN-LAST:event_clearButtonActionPerformed

    private void printReceiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReceiptButtonActionPerformed
        int customerRespond = JOptionPane.showConfirmDialog(null, "Are you sure you want to print Receipt?", "Print Receipt",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (customerRespond == JOptionPane.YES_OPTION) {
            try {
                result.clear();
                if (quantity.isEmpty()) {
                    throw new MyExceptions("You did not order anything yet");
                } else {
                    Date date = new Date();
                    result.add("Date:" + date.getDate() + "/" + (date.getMonth() + 1) + "/" + (date.getYear() + 1900)
                + "  -  Time: " + date.getHours() + " : " + date.getMinutes());
                    result.add("Universiti Malaysia Terengganu 20200");
                    result.add("Refernce No " + (count + 102464));
                    result.add(String.format("\n%25S", "Receipt No(" + count + ")"));
                    result.add("-------------------------------------------");
                    result.add(String.format(" %-18s %-10s   %s", "Item", "Quantity", "Subtotal"));
                    result.add("-------------------------------------------");

                    for (int i = 0; i < quantity.size(); i++) {
                        if (quantity.get(i) > 0) {
                            result.add(String.format("%-15s: %10d %13.2f", foodMenu.get(i), quantity.get(i), (quantity.get(i) * foodPrice.get(i))));

                        }
                    }
                    if(result.size()<=7){
                        throw new MyExceptions("You did not order anything yet");
                    }
                    result.add("-------------------------------------------");
                    result.add(String.format("%-15s:%25.2f", "Total", total));
                    result.add("-------------------------------------------");
                    result.add("\n- Under the supervision of Dr.\n"
                            + "NOOR HAFHIZAH BINTI ABD.RAHIM ABD RAHIM");
                    result.add("\n- This Program was Created By:");
                    result.add("\t1. OMAR ISMAIL ABDJALEEL ALOMORY\n"
                            + "\t2. MOHAMAD HAZIM BIN MOHD SHAKRI\n"
                            + "\t3. FARIS ISKANDAR BIN ABD RAHMAN\n"
                            + "\t4. ARUN MUGILAN A/L SARGUNAN");
                    receiptFile = new FileWriter("Customer Order No (" + count + ").txt");
                    if (result.size() > 5) {
                        for (int i = 0; i < result.size(); i++) {
                            receiptFile.append(result.get(i) + "\n");
                        }
                        this.dispose();
                        MainMenu newCusomerOrder = new MainMenu(foodMenu, foodPrice,log);
                        newCusomerOrder.setVisible(true);
                    }

                    receiptFile.close();

                    JOptionPane.showMessageDialog(null, "Your Receipt No (" + count + ") is Printed ");
                    count++;
                }
            } catch (IOException | MyExceptions a) {
                JOptionPane.showMessageDialog(null, a.getMessage(), a.getClass().getSimpleName(), JOptionPane.ERROR_MESSAGE);
            }

        } else if (customerRespond == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_printReceiptButtonActionPerformed

    private void ItemNoTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_ItemNoTextFieldCaretUpdate
 
        String icon = ItemNoTextField.getText();

        switch (icon) {
            case "1":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigBurger.png")));
                break;
            case "2":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smallBurger.png")));
                break;
            case "3":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toppng.com-cooked-chicken-png-500x387.png")));
                break;
            case "4":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salad.png")));
                break;
            case "5":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apple-juice.png")));
                break;
            case "6":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orange-juice.png")));
                break;
            case "7":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green-tea.png")));
                break;
            case "8":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TeaO1.png")));
                break;
            case "":
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res.png")));
                break;                
            default:
                iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/out of order.png")));
        
        }
 
    }//GEN-LAST:event_ItemNoTextFieldCaretUpdate

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ItemNoTextField;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton printReceiptButton;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables
}
